---
- name: import generic tasks
  import_tasks: common.yml

- name: include vars
  include_vars: vars/vars.yml

- name: install rabbitmq-server
  apt: name=rabbitmq-server state=latest
- name: check openstack user
  shell: rabbitmqctl list_users | grep -q openstack
  register: user
  ignore_errors: True
- name: create rabbitmq openstack user
  command: rabbitmqctl add_user openstack {{ password }}
  when: user is failed
- name: configure rights
  command: rabbitmqctl set_permissions openstack ".*" ".*" ".*"
  when: user is failed
